name: idc-uat

networks:
  uat_network:
    name: uat_network
    driver: bridge
    external: true

volumes:
  uat_cache:
  uat_vanna_chroma:
  uat_profile_embedding:
  uat_nltk_data:
  uat_output:
  uat_logs:
  uat_ml_models:
  uat_uploads:
  uat_chromadb:
  uat_whisper:
  uat_paddleocr:
  uat_chroma_model:
  uat_graph_file_uploads:
  uat_sql_uploads:

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: uat-flask-app
    restart: always
    ports:
      - "5004:5000"  # Use different port from dev
    env_file:
      - .env
    environment:
      - FLASK_ENV=development
      - CELERY_BROKER_URL=redis://uat-redis:6379/0
      - CELERY_RESULT_BACKEND=redis://uat-redis:6379/0
    depends_on:
      - redis
    volumes:
      - uat_cache:/myapp/cache
      - uat_vanna_chroma:/myapp/cache/vanna-chroma
      - uat_profile_embedding:/myapp/cache/profiling_embedding
      - uat_logs:/myapp/cache/logs
      - uat_sql_uploads:/myapp/cache/sql-uploads
      - uat_graph_file_uploads:/myapp/cache/graph-file-uploads
      - uat_ml_models:/myapp/cache/ml-model
      - uat_uploads:/myapp/cache/uploads
      - uat_chromadb:/myapp/cache/chromadb
      - uat_chroma_model:/root/.cache/chroma
      - uat_output:/myapp/cache/output
      - uat_whisper:/root/.cache/whisper
      - uat_paddleocr:/root/.paddleocr
      - uat_nltk_data:/usr/share/nltk_data


    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - uat_network

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: uat-celery-worker
    restart: always
    command: celery -A celery_worker.celery worker --autoscale=10,2 --loglevel=info -Q cpu_queue
    env_file:
      - .env
    environment:
      - FLASK_ENV=production
      - CELERY_BROKER_URL=redis://uat-redis:6379/0
      - CELERY_RESULT_BACKEND=redis://uat-redis:6379/0
    depends_on:
      - redis
    volumes:
      - uat_cache:/myapp/cache
      - uat_vanna_chroma:/myapp/cache/vanna-chroma
      - uat_profile_embedding:/myapp/cache/profiling_embedding
      - uat_logs:/myapp/cache/logs
      - uat_output:/myapp/cache/output
      - uat_sql_uploads:/myapp/cache/sql-uploads
      - uat_graph_file_uploads:/myapp/cache/graph-file-uploads
      - uat_ml_models:/myapp/cache/ml-model
      - uat_uploads:/myapp/cache/uploads
      - uat_chromadb:/myapp/cache/chromadb
      - uat_whisper:/root/.cache/whisper
      - uat_paddleocr:/root/.paddleocr
      - uat_nltk_data:/usr/share/nltk_data
      - uat_chroma_model:/root/.cache/chroma


    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - uat_network

  celery-worker-gpu:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: uat-celery-worker-gpu
    restart: always
    command: celery -A celery_worker.celery worker --pool=solo --loglevel=info -Q gpu_queue
    env_file:
      - .env
    environment:
      - FLASK_ENV=production
      - CELERY_BROKER_URL=redis://uat-redis:6379/0
      - CELERY_RESULT_BACKEND=redis://uat-redis:6379/0
    depends_on:
      - redis
    volumes:
      - uat_cache:/myapp/cache
      - uat_vanna_chroma:/myapp/cache/vanna-chroma
      - uat_profile_embedding:/myapp/cache/profiling_embedding
      - uat_logs:/myapp/cache/logs
      - uat_output:/myapp/cache/output
      - uat_sql_uploads:/myapp/cache/sql-uploads
      - uat_graph_file_uploads:/myapp/cache/graph-file-uploads
      - uat_ml_models:/myapp/cache/ml-model
      - uat_uploads:/myapp/cache/uploads
      - uat_chromadb:/myapp/cache/chromadb
      - uat_whisper:/root/.cache/whisper
      - uat_paddleocr:/root/.paddleocr
      - uat_nltk_data:/usr/share/nltk_data
      - uat_chroma_model:/root/.cache/chroma

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - uat_network

  redis:
    image: "redislabs/redisgraph:latest"
    container_name: uat-redis
    ports:
      - "6383:6379"  # Use a different Redis port from dev
    restart: always
    networks:
      - uat_network