from flask import current_app
import psycopg2
import json
import os
from psycopg2.extras import Json



class DatabaseManager:
    _instance = None

    def __new__(cls):
        if cls._instance is None:
            cls._instance = super(DatabaseManager, cls).__new__(cls)
        return cls._instance

    def __init__(self):
        # Prevent reinitialization on subsequent calls
        if hasattr(self, "_initialized") and self._initialized:
            return
        try:
            self.conn = psycopg2.connect(os.getenv("DSN_postgres"))
            self.conn.autocommit = True
            self.cur = self.conn.cursor()
            self.setup_tables()
            current_app.logger.info("Connected to the database and tables are set up.")
            self._initialized = True
        except Exception as e:
            current_app.logger.info("Error connecting to the database:", e)
            raise

    def setup_tables(self):
        ddl_script = """
        -- Create file_metadata table
        CREATE TABLE IF NOT EXISTS public.file_metadata
        (
            file_id character varying NOT NULL,
            file_name character varying NOT NULL UNIQUE,
            file_type character varying,
            creation_time timestamp without time zone NOT NULL,
            last_modification_time timestamp without time zone,
            created_by character varying,
            modified_by character varying,
            file_size text,
            CONSTRAINT file_metadata_pkey PRIMARY KEY (file_name)
        );

        COMMENT ON TABLE public.file_metadata IS 'Contains the metadata of the file.';
        COMMENT ON COLUMN public.file_metadata.file_id IS 'ID of the file';
        COMMENT ON COLUMN public.file_metadata.file_name IS 'Name of the file. Primary key: unique identifier for a file.';
        COMMENT ON COLUMN public.file_metadata.file_type IS 'Type of file (e.g., PDF, DOCX).';
        COMMENT ON COLUMN public.file_metadata.creation_time IS 'Timestamp when the file record was created.';
        COMMENT ON COLUMN public.file_metadata.last_modification_time IS 'Timestamp when the file record was last updated.';
        COMMENT ON COLUMN public.file_metadata.created_by IS 'User ID (from USERS) who created the file record.';
        COMMENT ON COLUMN public.file_metadata.modified_by IS 'User ID (from USERS) who last updated the file record.';
        COMMENT ON COLUMN public.file_metadata.file_size IS 'Size of the file in bytes.';

        -- Create file_metadata_classification table
        CREATE TABLE IF NOT EXISTS public.file_metadata_classification
        (
            file_id character varying NOT NULL,
            file_name character varying NOT NULL UNIQUE,
            data_category character varying,
            sensitivity character varying,
            data_classifiers character varying,
            responsible_values text,
            retention_time numeric,
            word_count integer,
            creation_time timestamp without time zone NOT NULL,
            last_modification_time timestamp without time zone,
            created_by character varying,
            modified_by character varying,
            CONSTRAINT file_metadata_classification_pkey PRIMARY KEY (file_name)
        );

        COMMENT ON TABLE public.file_metadata_classification IS 'Contains detailed classification information generated by the LLM about the file.';
        COMMENT ON COLUMN public.file_metadata_classification.file_id IS 'Primary key and foreign key referencing FILE_METADATA; identifies the file.';
        COMMENT ON COLUMN public.file_metadata_classification.file_name IS 'Name of the file (redundantly stored for classification context).';
        COMMENT ON COLUMN public.file_metadata_classification.data_category IS 'Describes what the document is all about.';
        COMMENT ON COLUMN public.file_metadata_classification.sensitivity IS 'Sensitivity assigned according to categories: Public, Internal, Confidential, Restricted, Private, Critical, Regulatory.';
        COMMENT ON COLUMN public.file_metadata_classification.data_classifiers IS 'Lists the kinds of data included in the document.';
        COMMENT ON COLUMN public.file_metadata_classification.responsible_values IS 'Values that determine sensitivity and retention periods.';
        COMMENT ON COLUMN public.file_metadata_classification.retention_time IS 'Retention period for storing the document.';
        COMMENT ON COLUMN public.file_metadata_classification.word_count IS 'Number of words present in the document.';
        COMMENT ON COLUMN public.file_metadata_classification.creation_time IS 'Timestamp when the classification record was created.';
        COMMENT ON COLUMN public.file_metadata_classification.last_modification_time IS 'Timestamp when the classification record was last updated.';
        COMMENT ON COLUMN public.file_metadata_classification.created_by IS 'User ID (from USERS) who created the classification record.';
        COMMENT ON COLUMN public.file_metadata_classification.modified_by IS 'User ID (from USERS) who last updated the classification record.';

        DO $$
        BEGIN
        IF NOT EXISTS (
            SELECT 1 FROM pg_constraint
            WHERE conname = 'file_metadata_classification_file_name_fkey'
        ) THEN
            ALTER TABLE public.file_metadata_classification
            ADD CONSTRAINT file_metadata_classification_file_name_fkey
            FOREIGN KEY (file_name)
            REFERENCES public.file_metadata (file_name)
            ON UPDATE NO ACTION
            ON DELETE NO ACTION;
        END IF;
        END $$;

        -- Create query_responses table
        CREATE TABLE IF NOT EXISTS public.query_reponses
        (
            query_response_id serial PRIMARY KEY,
            query text NOT NULL,
            response text,
            chatbot character varying,
            model_for_response_generation character varying,
            evaluation_method character varying,
            hallucination numeric,
            hallucination_reason text,
            relevance numeric,
            relevance_reason text,
            creation_time timestamp without time zone NOT NULL,
            last_modification_time timestamp without time zone,
            created_by character varying,
            modified_by character varying
        );
        COMMENT ON TABLE public.query_reponses IS 'Contains all queries and corresponding GPT responses for both "Solix GPT" and "Solix Governance GPT."';
        COMMENT ON COLUMN public.query_reponses.query_response_id IS 'Primary key: unique identifier for a query-response pair.';
        COMMENT ON COLUMN public.query_reponses.query IS 'The text of the query submitted by the user.';
        COMMENT ON COLUMN public.query_reponses.response IS 'The response generated by the GPT system.';
        COMMENT ON COLUMN public.query_reponses.chatbot IS 'Identifier for the chatbot (e.g., ChatGPT, Bard) used to generate the response.';
        COMMENT ON COLUMN public.query_reponses.model_for_response_generation IS 'Specifies the language model used (e.g., GPT-4).';
        COMMENT ON COLUMN public.query_reponses.evaluation_method IS 'Specifies the evaluation methodology used- LLM as Judge/Cosine similarity';
        COMMENT ON COLUMN public.query_reponses.hallucination IS 'Score indicating potential hallucination in the generated response.';
        COMMENT ON COLUMN public.query_reponses.relevance IS 'Score indicating the relevance of the response to the query.';
        COMMENT ON COLUMN public.query_reponses.creation_time IS 'Timestamp when the query-response record was created.';
        COMMENT ON COLUMN public.query_reponses.last_modification_time IS 'Timestamp when the query-response record was last updated.';
        COMMENT ON COLUMN public.query_reponses.created_by IS 'User ID (from USERS) who initiated the query.';
        COMMENT ON COLUMN public.query_reponses.modified_by IS 'User ID (from USERS) who last updated the query-response record.';
        COMMENT ON COLUMN public.query_reponses.hallucination_reason IS 'Explanation for the hallucination score.';
        COMMENT ON COLUMN public.query_reponses.relevance_reason IS 'Explanation for the relevance score.';

       -- Create file_evaluation table with a unique constraint on file_name
        CREATE TABLE IF NOT EXISTS public.file_evaluation
        (
            evaluation_id serial PRIMARY KEY,
            file_name character varying NOT NULL UNIQUE,
            hallucination numeric,
            relevance numeric,
            creation_time timestamp without time zone NOT NULL,
            last_modification_time timestamp without time zone,
            created_by character varying,
            modified_by character varying,
            CONSTRAINT file_evaluation_file_name_fkey
                FOREIGN KEY (file_name)
                REFERENCES public.file_metadata (file_name)
                ON UPDATE NO ACTION
                ON DELETE NO ACTION
            
        );
        COMMENT ON TABLE public.file_evaluation IS 'Stores evaluation details for a file.';



        -- Create clusters table
        CREATE TABLE IF NOT EXISTS public.clusters
        (
            cluster_id serial PRIMARY KEY,
            data_category character varying NOT NULL,
            num_files integer,
            file_list text[],
            relevance numeric,
            hallucination numeric,
            creation_time timestamp without time zone NOT NULL,
            last_modification_time timestamp without time zone,
            CONSTRAINT unique_data_category UNIQUE (data_category)
        );
        COMMENT ON TABLE public.clusters IS 'Contains cluster grouping information and aggregated evaluation details.';
        COMMENT ON COLUMN public.clusters.data_category IS 'Data Label associated with the cluster.';
        COMMENT ON COLUMN public.clusters.num_files IS 'Number of files in the cluster.';
        COMMENT ON COLUMN public.clusters.file_list IS 'Array of file IDs belonging to the cluster (or a comma-separated list).';
        COMMENT ON COLUMN public.clusters.relevance IS 'Aggregated relevance score for the cluster.';
        COMMENT ON COLUMN public.clusters.hallucination IS 'Aggregated hallucination score for the cluster.';
        COMMENT ON COLUMN public.clusters.creation_time IS 'Timestamp when the cluster record was created.';
        COMMENT ON COLUMN public.clusters.last_modification_time IS 'Timestamp when the cluster record was last updated.';

        -- Create human_altered_table
        CREATE TABLE IF NOT EXISTS public.human_altered_table
        (
            file_id                CHARACTER VARYING          NOT NULL    UNIQUE,
            file_name              TEXT                       NOT NULL    UNIQUE,
            data_category          TEXT,
            sensitivity            TEXT,
            data_classifiers       TEXT,
            responsible_values     TEXT,
            retention_time         NUMERIC,
            word_count             INTEGER,
            reason_for_change      TEXT,
            creation_time          TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
            last_modification_time TIMESTAMP WITHOUT TIME ZONE,
            created_by             TEXT,
            modified_by            TEXT,
            CONSTRAINT human_altered_table_pkey PRIMARY KEY (file_name), 
            CONSTRAINT human_altered_table_file_name_fkey
                FOREIGN KEY (file_name)
                REFERENCES public.file_metadata (file_name)
                ON UPDATE NO ACTION
                ON DELETE NO ACTION
        );

        -- Create hitl_updated_table
        CREATE TABLE IF NOT EXISTS public.hitl_updated_table
        (
            file_id                CHARACTER VARYING         NOT NULL    UNIQUE,
            file_name              CHARACTER VARYING         NOT NULL    UNIQUE,
            data_category          CHARACTER VARYING,
            sensitivity            CHARACTER VARYING,
            data_classifiers       CHARACTER VARYING,
            responsible_values     TEXT,
            retention_time         NUMERIC,
            word_count             INTEGER,
            reason_for_change      TEXT,
            creation_time          TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
            last_modification_time TIMESTAMP WITHOUT TIME ZONE,
            created_by             CHARACTER VARYING,
            modified_by            CHARACTER VARYING,
            CONSTRAINT hitl_updated_table_pkey PRIMARY KEY (file_name),
            CONSTRAINT hitl_updated_table_file_name_fkey
                FOREIGN KEY (file_name)
                REFERENCES public.file_metadata (file_name)
                ON UPDATE NO ACTION
                ON DELETE NO ACTION
        );

            

        -- Comments on human_altered_table
        COMMENT ON TABLE public.human_altered_table IS
            'Contains detailed classification information generated or modified by human-in-the-loop processes.';
        COMMENT ON COLUMN public.human_altered_table.file_id IS
            'Primary key (UUID) and foreign key referencing public.file_metadata(file_id); identifies the file.';
        COMMENT ON COLUMN public.human_altered_table.file_name IS
            'Name of the file (redundantly stored for classification context).';
        COMMENT ON COLUMN public.human_altered_table.data_category IS
            'Describes what the document is all about.';
        COMMENT ON COLUMN public.human_altered_table.sensitivity IS
            'Sensitivity assigned according to categories: Public, Internal, Confidential, Restricted, Private, Critical, Regulatory.';
        COMMENT ON COLUMN public.human_altered_table.data_classifiers IS
            'Lists the kinds of data included in the document.';
        COMMENT ON COLUMN public.human_altered_table.responsible_values IS
            'Values that determine sensitivity and retention periods.';
        COMMENT ON COLUMN public.human_altered_table.retention_time IS
            'Retention period for storing the document (numeric).';
        COMMENT ON COLUMN public.human_altered_table.word_count IS
            'Number of words present in the document.';
        COMMENT ON COLUMN public.human_altered_table.reason_for_change IS
            'Text explaining why the record was changed by a human in the HITL process.';
        COMMENT ON COLUMN public.human_altered_table.creation_time IS
            'Timestamp when the human-altered record was created.';
        COMMENT ON COLUMN public.human_altered_table.last_modification_time IS
            'Timestamp when the human-altered record was last updated.';
        COMMENT ON COLUMN public.human_altered_table.created_by IS
            'User ID (from USERS) who created the human-altered record.';
        COMMENT ON COLUMN public.human_altered_table.modified_by IS
            'User ID (from USERS) who last updated the human-altered record.';

        -- Comments on hitl_updated_table
        COMMENT ON TABLE public.hitl_updated_table IS
            'Contains updated classification information consolidated from human-in-the-loop feedback.';
        COMMENT ON COLUMN public.hitl_updated_table.file_id IS
            'Primary key and foreign key referencing public.file_metadata(file_id); identifies the file.';
        COMMENT ON COLUMN public.hitl_updated_table.file_name IS
            'Name of the file (redundantly stored for classification context).';
        COMMENT ON COLUMN public.hitl_updated_table.data_category IS
            'Describes what the document is all about.';
        COMMENT ON COLUMN public.hitl_updated_table.sensitivity IS
            'Sensitivity assigned according to categories: Public, Internal, Confidential, Restricted, Private, Critical, Regulatory.';
        COMMENT ON COLUMN public.hitl_updated_table.data_classifiers IS
            'Lists the kinds of data included in the document.';
        COMMENT ON COLUMN public.hitl_updated_table.responsible_values IS
            'Values that determine sensitivity and retention periods.';
        COMMENT ON COLUMN public.hitl_updated_table.retention_time IS
            'Retention period for storing the document (numeric).';
        COMMENT ON COLUMN public.hitl_updated_table.word_count IS
            'Number of words present in the document.';
        COMMENT ON COLUMN public.hitl_updated_table.reason_for_change IS
            'Text explaining why the record was changed or updated in the HITL workflow.';
        COMMENT ON COLUMN public.hitl_updated_table.creation_time IS
            'Timestamp when the updated record was created.';
        COMMENT ON COLUMN public.hitl_updated_table.last_modification_time IS
            'Timestamp when the updated record was last updated.';
        COMMENT ON COLUMN public.hitl_updated_table.created_by IS
            'User ID (from USERS) who created the updated record.';
        COMMENT ON COLUMN public.hitl_updated_table.modified_by IS
            'User ID (from USERS) who last updated the record.';

        
        """
        try:
            self.cur.execute(ddl_script)
            current_app.logger.info("DDL executed successfully.")
        except Exception as e:
            current_app.logger.info("Error setting up tables:", e)
            raise

    # --------------------------------------------------------------------------
    # Methods to add data into each table
    # --------------------------------------------------------------------------
    def add_file_metadata(self, file_metadata_data):
        current_app.logger.info(f"Started add_file_metadata, {file_metadata_data}")
        file_id = file_metadata_data['file_id']
        file_name = file_metadata_data['file_name']
        file_type = file_metadata_data['file_type']
        creation_time = file_metadata_data['created_time']
        last_modification_time = file_metadata_data['last_modification_time']
        created_by = file_metadata_data['created_by']
        modified_by = file_metadata_data['modified_by']
        file_size = file_metadata_data['file_size']
        current_app.logger.info("Called the add_file_metadata")
        sql = """
        INSERT INTO public.file_metadata (
            file_id, file_name, file_type, creation_time, last_modification_time, created_by, modified_by, file_size
        ) VALUES (
            %s, %s, %s, NOW(), NOW(), %s, %s, %s
        )
        ON CONFLICT (file_name)
        DO UPDATE SET
            file_id                = EXCLUDED.file_id,
            file_type              = EXCLUDED.file_type,
            file_size              = EXCLUDED.file_size,
            last_modification_time = NOW(),
            modified_by            = EXCLUDED.modified_by;
        """
        try:
            with self.conn.cursor() as cur:
                cur.execute(sql, (file_id, file_name, file_type, created_by, modified_by, file_size))
                self.conn.commit()
            current_app.logger.info(f"File metadata '{file_id}' inserted/updated successfully.")
        except Exception as e:
            self.conn.rollback()
            current_app.logger.error("Error inserting file_metadata", exc_info=True)
            raise e

    def add_file_metadata_classification(self, file_metadata_data_classification):
        current_app.logger.info(f"Started add_file_metadata_classification, {file_metadata_data_classification}")
        file_id = file_metadata_data_classification['file_id']
        file_name = file_metadata_data_classification['file_name']
        data_category = file_metadata_data_classification['data_category']
        sensitivity = file_metadata_data_classification['sensitivity']
        data_classifiers = file_metadata_data_classification['data_classifiers']
        responsible_values = file_metadata_data_classification['responsible_values']
        retention_time = file_metadata_data_classification['retention_time']
        word_count = file_metadata_data_classification['word_count']
        created_by = file_metadata_data_classification['created_by']
        modified_by = file_metadata_data_classification['modified_by']
    
        current_app.logger.info("Called the add_file_metadata_classification")
        sql = """
        INSERT INTO public.file_metadata_classification (
            file_id, file_name, data_category, sensitivity, data_classifiers, responsible_values,
            retention_time, word_count, creation_time, last_modification_time, created_by, modified_by
        ) VALUES (
            %s, %s, %s, %s, %s, %s, %s, %s, NOW(), NOW(), %s, %s
        )
        ON CONFLICT (file_name) DO UPDATE SET
            file_id = EXCLUDED.file_id,
            data_category = EXCLUDED.data_category,
            sensitivity = EXCLUDED.sensitivity,
            data_classifiers = EXCLUDED.data_classifiers,
            responsible_values = EXCLUDED.responsible_values,
            retention_time = EXCLUDED.retention_time,
            word_count = EXCLUDED.word_count,
            last_modification_time = NOW(),
            modified_by = EXCLUDED.modified_by;
        """
        try:
            with self.conn.cursor() as cur:
                cur.execute(sql, (file_id, file_name, data_category, sensitivity, data_classifiers,
                                  responsible_values, retention_time, word_count, created_by, modified_by))
                self.conn.commit()
                current_app.logger.info(f"File metadata classification '{file_name}' inserted/updated successfully.")
        except Exception as e:
            self.conn.rollback()
            current_app.logger.error("Error inserting file_metadata_classification", exc_info=True)
            raise e

    def add_query_response(self, query_response_data):
        current_app.logger.info(f"Started add_query_response with data: {query_response_data}")
    
        query_text   = query_response_data['query']
        response     = query_response_data['response']
        chatbot      = query_response_data['chatbot']
        model_for_response_generation    = query_response_data['model_for_response_generation']
        evaluation_method= query_response_data['evaluation_method']
        hallucination = query_response_data['hallucination']
        hallucination_reason = query_response_data['hallucination_reason']
        relevance     = query_response_data['relevance']
        relevance_reason = query_response_data['relevance_reason']
        created_by    = query_response_data['created_by']
        modified_by   = query_response_data['modified_by']

        sql = """
            INSERT INTO public.query_reponses (
                query, response, chatbot, model_for_response_generation, evaluation_method, hallucination, relevance,
                hallucination_reason, relevance_reason,
                creation_time, last_modification_time, created_by, modified_by
            ) VALUES (
                %s, %s, %s, %s, %s, %s, %s, %s, %s, NOW(), NOW(), %s, %s
            )
        """
        try:
            with self.conn.cursor() as cur:
                cur.execute(sql, (
                    query_text, response, chatbot, model_for_response_generation, evaluation_method, hallucination, relevance,
                    hallucination_reason, relevance_reason, created_by, modified_by
                ))
            self.conn.commit()
        except Exception as e:
            self.conn.rollback()
            current_app.logger.error("Error inserting query response", exc_info=True)
            raise e

    def add_file_evaluation(self, evaluation_data):
        current_app.logger.info(f"Started add_file_evaluation, data: {evaluation_data}")
        
        file_name = evaluation_data.get("file_name")
        if file_name is None:
            current_app.logger.warning("file_name is None; defaulting to 'unknown'")
            file_name = "unknown"
        else:
            file_name = file_name.strip()
        
        # These values may be None if the particular evaluation didn't calculate them.
        hallucination = evaluation_data.get("hallucination")
        relevance = evaluation_data.get("relevance")
        created_by = evaluation_data.get("created_by", "system")
        modified_by = evaluation_data.get("modified_by", "system")

        sql = """
        INSERT INTO public.file_evaluation (
            file_name, hallucination, relevance, creation_time, last_modification_time, created_by, modified_by
        ) VALUES (
            %s, %s, %s, NOW(), NOW(), %s, %s
        )
        ON CONFLICT (file_name) DO UPDATE SET
            hallucination = COALESCE(EXCLUDED.hallucination, public.file_evaluation.hallucination),
            relevance = COALESCE(EXCLUDED.relevance, public.file_evaluation.relevance),
            last_modification_time = NOW(),
            modified_by = EXCLUDED.modified_by;
        """
        
        try:
            with self.conn.cursor() as cur:
                cur.execute(sql, (file_name, hallucination, relevance, created_by, modified_by))
                self.conn.commit()
            current_app.logger.info(f"File evaluation for '{file_name}' inserted/updated successfully.")
        except Exception as e:
            self.conn.rollback()
            current_app.logger.error("Error inserting file_evaluation", exc_info=True)
            raise e




    def add_cluster(self, cluster_data):
        """
        Inserts or updates a record in the clusters table.
        Expected cluster_data keys:
            data_category, num_files, file_list, relevance, hallucination
        """
        current_app.logger.info(f"Started add_cluster, data: {cluster_data}")
        data_category = cluster_data.get("data_category")
        num_files = cluster_data.get("num_files")
        file_list = cluster_data.get("file_list")  # expects a list of file IDs (strings)
        relevance = cluster_data.get("relevance")
        hallucination = cluster_data.get("hallucination")

        sql = """
        INSERT INTO public.clusters (
            data_category, num_files, file_list, relevance, hallucination, creation_time, last_modification_time
        ) VALUES (
            %s, %s, %s, %s, %s, NOW(), NOW()
        )
        ON CONFLICT (data_category) DO UPDATE SET
            num_files = EXCLUDED.num_files,
            file_list = EXCLUDED.file_list,
            relevance = EXCLUDED.relevance,
            hallucination = EXCLUDED.hallucination,
            last_modification_time = NOW();
        """
        try:
            with self.conn.cursor() as cur:
                cur.execute(sql, (data_category, num_files, file_list, relevance, hallucination))
                self.conn.commit()
            current_app.logger.info(f"Cluster '{data_category}' inserted/updated successfully.")
        except Exception as e:
            self.conn.rollback()
            current_app.logger.error("Error inserting cluster data", exc_info=True)
            raise e

    def delete_all_rows(self):
        """
        Deletes all rows from all tables in the current database.
        Uses TRUNCATE with CASCADE to handle foreign key dependencies.
        """
        try:
            truncate_query = """
            TRUNCATE TABLE 
                public.query_reponses,  
                public.file_metadata_classification, 
                public.file_metadata,
                public.file_evaluation,
                public.clusters,
                public.hitl_updated_table,
                public.human_altered_table
            CASCADE;
            """
            self.cur.execute(truncate_query)
            current_app.logger.info("All rows from all tables have been deleted.")
        except Exception as e:
            current_app.logger.error("Error deleting all rows from tables: %s", e)
            raise
